### ISSUE TITLE
Document custom components

### ISSUE THREAD

**Issue by davidmytton** [arcjet/arcjet-docs#250] opened 2024-11-12 09:55 UTC
I left this in as an example of how to use the component, but it'd be better moved to some docs. @morekid perhaps you can document the custom components in the readme?

_Originally posted by @davidmytton in https://github.com/arcjet/arcjet-docs/issues/248#issuecomment-2470082650_

**Comment by morekid** [comment] 2024-11-21 12:21
@davidmytton closing as it's a duplicate of #239.

**Closed by morekid** 2024-11-21 12:21 UTC
